#!/usr/bin/env python3
"""Inventory of spell ids hardcoded into the effect and aura handlers.

Issue 20 in review-spells.md is a count -- 445 distinct ids -- and a count is not
something anyone can work through. This produces the list: every hardcoded id,
where it is, which function it is in, and which of three shapes it takes. That
turns the issue into a burn-down rather than an argument.

Run it from anywhere; it writes hardcoded-spells.md beside itself.

    python3 hardcoded-spells.py

The three shapes, in the order they are worth attacking:

  dispatch    `case <id>:` inside a switch on a spell id. These are the bulk and
              the mechanical ones: a switch keyed on a spell id, producing a
              fixed result, is a table that has not been written yet. Stage 6 of
              the optimization plan moved two of them (Spell::cast and
              HandleSpellSpecificBoosts) to load-time data without changing a
              rule; the rest follow the same path.

  comparison  `m_spellInfo->ID == <id>`, one spell singled out mid-function.
              Usually a special case bolted onto generic code, and usually the
              hardest to express as data, because what it does is not "cast X"
              but "behave differently here".

  reference   a literal id passed to CastSpell, RemoveAurasDueToSpell and
              friends. Often already expressible as a spell_linked row -- these
              are the ones to check against the existing side tables first,
              because some of them are duplicates of rows that already exist.
"""

import os
import re
import collections

HERE = os.path.dirname(os.path.abspath(__file__))

# Spell ids in 1.12 run to about 30000. Below 100 the literal is far more likely
# to be an index, a percentage or a count, and including those would bury the
# real entries in noise -- the inventory is only useful if it can be trusted
# without checking every line by hand.
ID_MIN, ID_MAX = 100, 40000

RE_CASE = re.compile(r'^\s*case\s+(\d{3,5})\s*:')
RE_COMPARE = re.compile(r'(?:ID|Id|GetId\(\)|spellId|spell_id)\s*==\s*(\d{3,5})\b')
RE_CALL = re.compile(
    r'\b(CastSpell|CastCustomSpell|RemoveAurasDueToSpell|RemoveAurasByCasterSpell|'
    r'RemoveAurasAtMechanicImmunity|SendSpellMiss|AddPrecastSpell|AddTriggeredSpell|'
    r'HasAura|GetAura|RemoveSpellCooldown|SetAuraDuration)\s*\(')
RE_LITERAL = re.compile(r'(?<![\w>.])(\d{3,5})(?![\w.])')

# A function definition at column zero: `void Spell::EffectDummy(...)`.
RE_FUNC = re.compile(r'^[A-Za-z_][\w:<>,\s\*&]*\b([A-Za-z_]\w*::[A-Za-z_]\w*)\s*\(')


def in_range(value):
    return ID_MIN <= int(value) <= ID_MAX


def scan(path):
    """Yield (line_no, shape, spell_id, function, text) for one file."""
    func = '(file scope)'
    with open(path, encoding='utf-8', errors='replace') as handle:
        for n, line in enumerate(handle, 1):
            match = RE_FUNC.match(line)
            if match:
                func = match.group(1)

            stripped = line.strip()
            if stripped.startswith('//') or stripped.startswith('*'):
                continue

            hit = RE_CASE.match(line)
            if hit and in_range(hit.group(1)):
                yield n, 'dispatch', int(hit.group(1)), func, stripped
                continue

            found = False
            for value in RE_COMPARE.findall(line):
                if in_range(value):
                    yield n, 'comparison', int(value), func, stripped
                    found = True
            if found:
                continue

            if RE_CALL.search(line):
                for value in RE_LITERAL.findall(line):
                    if in_range(value):
                        yield n, 'reference', int(value), func, stripped


def main():
    names = sorted(
        f for f in os.listdir(HERE)
        if f.startswith('Spell') and f.endswith('.cpp')
    )

    rows = []
    for name in names:
        for entry in scan(os.path.join(HERE, name)):
            rows.append((name,) + entry)

    by_shape = collections.Counter(r[2] for r in rows)
    distinct = sorted({r[3] for r in rows})
    by_file = collections.Counter(r[0] for r in rows)

    out = os.path.join(HERE, 'hardcoded-spells.md')
    with open(out, 'w', encoding='utf-8', newline='\n') as md:
        md.write('# Hardcoded spell ids — inventory\n\n')
        md.write('Generated by `hardcoded-spells.py`. Re-run it; the numbers are '
                 'meant to go down.\n\n')
        md.write('This is the burn-down list behind Issue 20 in `review-spells.md`. '
                 'See that file for what the issue is and\nwhy the count matters; '
                 'see the docstring in the generator for what the three shapes mean '
                 'and which to attack first.\n\n')

        md.write('**%d sites, %d distinct spell ids.**\n\n' % (len(rows), len(distinct)))

        md.write('| shape | sites |\n| --- | ---: |\n')
        for shape in ('dispatch', 'comparison', 'reference'):
            md.write('| %s | %d |\n' % (shape, by_shape.get(shape, 0)))
        md.write('\n')

        md.write('| file | sites |\n| --- | ---: |\n')
        for name, count in by_file.most_common():
            md.write('| %s | %d |\n' % (name, count))
        md.write('\n')

        md.write('## By function\n\n')
        md.write('Ordered by how much is nailed into each one, because a function '
                 'with forty cases is one table\nwaiting to be written, and forty '
                 'functions with one case each are forty separate arguments.\n\n')

        per_func = collections.defaultdict(list)
        for name, line, shape, spell, func, text in rows:
            per_func[(name, func)].append((line, shape, spell, text))

        for (name, func), entries in sorted(
                per_func.items(), key=lambda kv: (-len(kv[1]), kv[0])):
            md.write('### `%s` — %s (%d)\n\n' % (func, name, len(entries)))
            for line, shape, spell, text in sorted(entries):
                md.write('- %s:%d `%d` *%s* — `%s`\n'
                         % (name, line, spell, shape, text.replace('`', "'")[:110]))
            md.write('\n')

    print('%d sites, %d distinct ids -> %s' % (len(rows), len(distinct), out))


if __name__ == '__main__':
    main()
