/**
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 * MaNGOS is a full featured server for World of Warcraft, supporting
 * the following clients: 1.12.x, 2.4.3, 3.3.5a, 4.3.4a and 5.4.8
 *
 * Copyright (C) 2005-2026 MaNGOS <https://www.getmangos.eu>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>.
 *
 * World of Warcraft, and all World of Warcraft or Warcraft art, images,
 * and lore are copyrighted by Blizzard Entertainment, Inc.
 */

#include "Revision.h"

// Generated by cmake/Revision.cmake into the build tree. Only this file has its
// directory on the include path (src/shared/CMakeLists.txt).
#include "BuildRevision.h"

#include <cstddef>

namespace
{
    Revision::DbVersion const s_worldDb =
    {
        "World", REVISION_WORLD_DB_VERSION, REVISION_WORLD_DB_STRUCTURE,
        REVISION_WORLD_DB_CONTENT, REVISION_WORLD_DB_UPDATE
    };

    Revision::DbVersion const s_realmDb =
    {
        "Realmd", REVISION_REALMD_DB_VERSION, REVISION_REALMD_DB_STRUCTURE,
        REVISION_REALMD_DB_CONTENT, REVISION_REALMD_DB_UPDATE
    };

    Revision::DbVersion const s_charDb =
    {
        "Character", REVISION_CHAR_DB_VERSION, REVISION_CHAR_DB_STRUCTURE,
        REVISION_CHAR_DB_CONTENT, REVISION_CHAR_DB_UPDATE
    };

    struct ConfigEntry
    {
        char const* name;
        char const* path;
        uint32 version;
    };

    // Indexed by Revision::ConfigFile.
    ConfigEntry const s_configs[] =
    {
        { "mangosd.conf",     REVISION_CONFIG_DIR "mangosd.conf",     REVISION_MANGOSD_CONF_VERSION   },
        { "realmd.conf",      REVISION_CONFIG_DIR "realmd.conf",      REVISION_REALMD_CONF_VERSION    },
        { "ahbot.conf",       REVISION_CONFIG_DIR "ahbot.conf",       REVISION_AHBOT_CONF_VERSION     },
        { "aiplayerbot.conf", REVISION_CONFIG_DIR "aiplayerbot.conf", REVISION_PLAYERBOT_CONF_VERSION },
    };

    static_assert(sizeof(s_configs) / sizeof(s_configs[0]) == std::size_t(Revision::ConfigFile::Playerbot) + 1,
                  "s_configs must list every Revision::ConfigFile, in order");
}

char const* Revision::GetRevisionStr()
{
    return REVISION_STR;
}

char const* Revision::GetElunaRevisionStr()
{
    return REVISION_ELUNA_STR;
}

char const* Revision::GetSD3RevisionStr()
{
    return REVISION_SD3_STR;
}

char const* Revision::GetFullRevision()
{
    return "Mangos revision: " REVISION_STR;
}

char const* Revision::GetHash()
{
    return REVISION_HASH;
}

char const* Revision::GetDate()
{
    return REVISION_DATE;
}

char const* Revision::GetPackageName()
{
    return REVISION_PACKAGE_NAME;
}

char const* Revision::GetProjectRevision()
{
    return REVISION_PROJECT_NR;
}

char const* Revision::GetBuildHost()
{
    return REVISION_BUILD_HOST;
}

Revision::DbVersion const& Revision::GetWorldDb()
{
    return s_worldDb;
}

Revision::DbVersion const& Revision::GetRealmDb()
{
    return s_realmDb;
}

Revision::DbVersion const& Revision::GetCharDb()
{
    return s_charDb;
}

char const* Revision::GetConfigName(ConfigFile file)
{
    return s_configs[std::size_t(file)].name;
}

char const* Revision::GetConfigPath(ConfigFile file)
{
    return s_configs[std::size_t(file)].path;
}

uint32 Revision::GetConfigVersion(ConfigFile file)
{
    return s_configs[std::size_t(file)].version;
}
